dubbo:
  registry:
    address: nacos://${nacos.address:127.0.0.1}:8848
    register-mode: instance
    username: nacos
    password: ${nacos.password}
    use-as-config-center: false
    use-as-metadata-center: false
  protocol:
#    name: dubbo
    name: tri
    port: 50051
  qos:
    enable: false
  application:
    name: dubbo-producer
    logger: slf4j
    qos-enable: false